FROM node:18

WORKDIR /app

# Copia apenas o package.json primeiro (para aproveitar cache)
COPY package*.json ./

# Instala dependências
RUN npm install

# Copia o resto do código
COPY . .

EXPOSE 3000
CMD ["npm", "start"]
