services:
  postgres:
    image: postgres:16
    container_name: postgres-doula
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: doula_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-doula
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doula_manager
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/doula_manager
      - JWT_SECRET_KEY=supersecreta-chave-aqui
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-doula
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8080 
      - REACT_APP_USE_MOCK=false
    volumes:
      - ./frontend/src:/app/src  # Mount source code
      - ./frontend/public:/app/public  # Mount public folder
      - /app/node_modules  # Preserve node_modules in container
    stdin_open: true
    tty: true
    depends_on:
      - backend
    restart: always
    
volumes:
  postgres_data: