services:
  postgres:
    image: postgres:16
    container_name: postgres-doula
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: doula_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doula_manager
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-doula
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: