services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      # Mapeia o arquivo doulamanager.db do host para o container
      - ./backend/doulamanager.db:/app/doulamanager.db
    depends_on: []

  # Futuro serviço do frontend (comentado por enquanto)
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   depends_on:
  #     - backend
