from typing import Protocol, Sequence, Optional
from infrastructure.db.entities.doula import Doula

class DoulaRepositoryPort(Protocol):
    async def create(self, doula: Doula) -> Doula: ...
    async def find_all(self) -> Sequence[Doula]: ...
    async def find_by_id(self, id_: int) -> Optional[Doula]: ...