from typing import Protocol, Sequence, Optional

from domain.models.doula_model import DoulaModel

class DoulaRepositoryPort(Protocol):
    async def create(self, doula: DoulaModel) -> DoulaModel: ...
    async def find_all(self) -> Sequence[DoulaModel]: ...
    async def find_by_id(self, id_: int) -> Optional[DoulaModel]: ...
    async def find_by_email(self, email: str) -> Optional[DoulaModel]: ...