from typing import Protocol, Sequence, Optional

from domain.models.lesson_model import LessonModel

class LessonRepositoryPort(Protocol):
    async def create(self, lesson: LessonModel) -> LessonModel: ...
    async def find_all(self, doula_id: int) -> Sequence[LessonModel]: ...
    async def find_by_id(self, id_: int) -> Optional[LessonModel]: ...