from typing import Protocol, Sequence, Optional

from infrastructure.db.entities import Lesson

class LessonRepositoryPort(Protocol):
    async def create(self, lesson: Lesson) -> Lesson: ...
    async def find_all(self) -> Sequence[Lesson]: ...
    async def find_by_id(self, id_: int) -> Optional[Lesson]: ...