spring:
  profiles:
    active: local
  jackson:
    property-naming-strategy: SNAKE_CASE
  application:
    name: doula-manager
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true